version: "3.7"

services:
  db:
    image: mysql:8.0.24
    restart: always
    environment:
      - MYSQL_DATABASE=4dgames
      - MYSQL_ROOT_PASSWORD=Holamundo12
  web:
    image: eduardosoy7/4dgames
    restart: always
    ports:
      - "8443:8443"
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/4dgames


